ALTER TABLE "EditorialPlan" ADD COLUMN "generationWindow" TEXT NOT NULL DEFAULT '02:00-06:00';
ALTER TABLE "EditorialPlan" ADD COLUMN "maxCostPerMonth" DOUBLE PRECISION NOT NULL DEFAULT 50;
ALTER TABLE "EditorialPlan" ADD COLUMN "lastRunAt" TIMESTAMP(3);
ALTER TABLE "EditorialPlan" ADD COLUMN "consecutiveFails" INTEGER NOT NULL DEFAULT 0;
