/* ContentFlow design-concept mock data (PT-BR) — classic script, global CF_DATA */
window.CF_DATA = {
  workspace: { name: 'Acme SaaS', plan: 'Pro', user: 'Leo Costa', email: 'leo@acme.com' },
  creatives: [
    { id: 'CF-184', title: 'Lançamento curso de IA para marketers', channel: 'Instagram', status: 'Pronto', statusKey: 'ok', chars: 248, updated: 'há 2 h', type: 'post', body: 'Pare de postar carrossel “bonito” que não vende.\n\nO novo curso ensina o sistema completo:\n1. Brand DNA\n2. Hooks que param o scroll\n3. Oferta em 5 slides\n\nLink na bio — turma de março.', tags: ['#marketing', '#saas', '#ia'], cta: 'Link na bio', tone: 'Direto', score: 78 },
    { id: 'CF-183', title: '7 erros de branding em SaaS B2B', channel: 'LinkedIn', status: 'Rascunho', statusKey: 'warn', chars: 1204, updated: 'ontem', type: 'post', body: 'Thread sobre posicionamento fraco, voz genérica e oferta invisível.\n\n1. Posicionamento genérico\n2. Voz copiada\n3. Oferta escondida\n…', tags: ['#branding', '#b2b'], cta: 'Comente qual erro você já cometeu', tone: 'Educativo', score: 71 },
    { id: 'CF-182', title: 'Carousel · checklist de posicionamento', channel: 'Instagram', status: 'Agendado', statusKey: 'blue', chars: null, updated: 'ontem', type: 'post', body: '6 slides educativos sobre posicionamento.', tags: ['#posicionamento'], cta: 'Salve o post', tone: 'Prático', score: 91 },
    { id: 'CF-181', title: 'Hook pack · objeções de preço', channel: 'TikTok', status: 'Pronto', statusKey: 'ok', chars: null, updated: '2 d', type: 'post', body: 'Série de hooks curtos para Reels/TikTok.', tags: ['#vendas'], cta: 'Segue para a parte 2', tone: 'Direto', score: 80 },
    { id: 'CF-180', title: 'Case · redução de CAC em 40%', channel: 'LinkedIn', status: 'Em revisão', statusKey: 'neutral', chars: 892, updated: '2 d', type: 'post', body: 'Case com métricas reais (anonimizado).', tags: ['#growth'], cta: 'DM para o playbook', tone: 'Autoridade', score: 84 },
    { id: 'CF-179', title: 'Reels 30s — benefícios do produto', channel: 'Video', status: 'Exportado', statusKey: 'blue', chars: null, updated: '3 d', type: 'script', body: 'Cena 1 (0–3s): Hook\nCena 2–5: Benefícios\nCena 6: CTA', tags: [], cta: 'Teste grátis', tone: 'Ágil', score: 76 },
    { id: 'CF-178', title: 'Sequência boas-vindas · e-mail 1/5', channel: 'Email', status: 'Pronto', statusKey: 'ok', chars: null, updated: '4 d', type: 'email', body: 'Assunto: Bem-vindo à Acme\nPreheader: Seu sistema de conteúdo começa aqui\n\nCorpo…', tags: [], cta: 'Ativar workspace', tone: 'Acolhedor', score: 73 },
    { id: 'CF-177', title: 'Meta ad · early bird março', channel: 'Ads', status: 'Rascunho', statusKey: 'warn', chars: null, updated: '5 d', type: 'ad', body: 'Headline: Garanta sua vaga\nPrimary text: …\n3 variantes', tags: [], cta: 'Saiba mais', tone: 'Urgente', score: 69 },
    { id: 'CF-176', title: 'Thread · por que Brand DNA importa', channel: 'Twitter', status: 'Pronto', statusKey: 'ok', chars: null, updated: '6 d', type: 'post', body: 'Thread 8 tweets.', tags: ['#content'], cta: 'RT se concordar', tone: 'Direto', score: 77 },
    { id: 'CF-175', title: 'Stories CTA · link na bio', channel: 'Instagram', status: 'Agendado', statusKey: 'blue', chars: null, updated: '1 sem', type: 'post', body: 'Frame 1 pergunta · Frame 2 CTA', tags: [], cta: 'Swipe up / link', tone: 'Casual', score: 70 },
    { id: 'CF-174', title: 'Newsletter · content ops da semana', channel: 'Email', status: 'Pronto', statusKey: 'ok', chars: null, updated: '1 sem', type: 'email', body: 'Resumo semanal + 3 links.', tags: [], cta: 'Ler no app', tone: 'Editorial', score: 75 },
    { id: 'CF-173', title: 'UGC brief · depoimento cliente', channel: 'Video', status: 'Em revisão', statusKey: 'neutral', chars: null, updated: '1 sem', type: 'script', body: 'Roteiro para cliente gravar depoimento 45s.', tags: [], cta: '—', tone: 'Humano', score: 72 },
  ],
  brands: [
    { id: 'b1', name: 'Acme SaaS', site: 'acme.com', status: 'Selecionada', industry: 'SaaS B2B', dna: true },
    { id: 'b2', name: 'Studio Norte', site: 'studionorte.com.br', status: 'Ativa', industry: 'Agência', dna: true },
    { id: 'b3', name: 'Casa Verde', site: 'casaverde.co', status: 'DNA incompleto', industry: 'E-commerce', dna: false },
  ],
  dna: {
    summary: { tagline: 'Conteúdo que opera, não enfeita.', industry: 'SaaS B2B · Marketing ops', audience: 'Heads de marketing e founders (20–200 pessoas).' },
    voice: { tone: 'direto, prático, sem hype', style: 'frases curtas, listas, exemplos reais', avoid: 'revolucionário, game-changer, emoji em excesso' },
    audience: { pains: ['inconsistência de conteúdo', 'dependência de freela'], desires: ['sistema previsível de posts'], objections: ['IA deixa tudo genérico'] },
    offer: { products: ['plataforma de content ops'], price: 'a partir de R$ 197/mês', diffs: ['Brand DNA + geração no mesmo fluxo'] },
    visual: { colors: '#18181b, #fafafa', style: 'limpo, tipográfico', type: 'sans geométrica' },
    constraints: ['sem promessa de resultado garantido', 'sem citar concorrente por nome', 'marca no slide final'],
  },
  ideas: [
    { n: 1, total: 5, title: 'O checklist que o seu social media finge que tem', hook: 'Se o seu calendário editorial cabe num post-it, você não tem calendário — tem torcida.', goal: 'Saves + clique para carrossel', angle: 'Confrontar improviso com sistema de 6 blocos', score: 82, platform: 'Instagram' },
    { n: 2, total: 5, title: 'Por que seu carrossel “bonito” não vende', hook: 'Design não é estratégia.', goal: 'Comentários', angle: 'Separar estética de oferta', score: 79, platform: 'LinkedIn' },
  ],
  jobs: [
    { id: 'job_91', title: 'Geração de imagens · CF-184', type: 'Images', status: 'Running', statusKey: 'blue', at: '14:40', cost: 'R$ 1,20' },
    { id: 'job_90', title: 'Extração Brand DNA · Casa Verde', type: 'DNA', status: 'Queued', statusKey: 'neutral', at: '14:38', cost: '—' },
    { id: 'job_88', title: 'Ideias carousel · Acme', type: 'Ideas', status: 'Done', statusKey: 'ok', at: '13:10', cost: 'R$ 0,15' },
    { id: 'job_85', title: 'Export PDF · projeto 12', type: 'Export', status: 'Failed', statusKey: 'red', at: '11:02', cost: 'R$ 0,00' },
  ],
  analytics: {
    kpis: [
      { l: 'Impressões', v: '128,4 mil', d: '+12,4% · 7d', up: true },
      { l: 'Engajamento', v: '4,8%', d: '+0,4 pp', up: true },
      { l: 'Saves', v: '2.140', d: '+18%', up: true },
      { l: 'Score médio', v: '72', d: 'estável', up: false },
    ],
    channels: [
      { name: 'Instagram', pc: 54 },
      { name: 'LinkedIn', pc: 28 },
      { name: 'TikTok', pc: 12 },
      { name: 'Outros', pc: 6 },
    ],
    top: [
      { title: 'Checklist de posicionamento', channel: 'Instagram', score: 91, eng: '6,2%', saves: 412 },
      { title: 'Rebrand before / after', channel: 'LinkedIn', score: 84, eng: '4,1%', saves: 188 },
      { title: '5 hooks que convertem', channel: 'TikTok', score: 79, eng: '5,5%', saves: 256 },
      { title: 'Oferta trimestral · early bird', channel: 'Instagram', score: 74, eng: '3,8%', saves: 97 },
    ],
  },
  calendar: {
    label: '9–15 mar 2026',
    channels: [
      { name: '@acme.br', platform: 'IG', color: '#e1306c' },
      { name: 'Acme Oficial', platform: 'LI', color: '#0a66c2' },
      { name: '@acme', platform: 'TT', color: '#111111' },
    ],
    days: [
      { name: 'Seg 9', events: [{ t: 'Carousel hooks', k: 'blue' }, { t: 'Draft ads', k: 'warn' }] },
      { name: 'Ter 10', events: [{ t: 'Stories CTA', k: 'ok' }] },
      { name: 'Qua 11', events: [{ t: 'Thread LI', k: 'blue' }, { t: 'Email #2', k: 'blue' }] },
      { name: 'Qui 12', events: [] },
      { name: 'Sex 13', events: [{ t: 'Reels 30s', k: 'blue' }] },
      { name: 'Sáb 14', events: [{ t: 'UGC repost', k: 'ok' }] },
      { name: 'Dom 15', events: [] },
    ],
  },
  editorial: [
    { name: 'Plano mensal Instagram · março', freq: '3×/sem', status: 'Ativo', statusKey: 'ok' },
    { name: 'LinkedIn thought leadership', freq: '2×/sem', status: 'Pausado', statusKey: 'warn' },
  ],
  templates: [
    { name: 'Educativo 6 slides', cat: 'Carousel', installs: 1240 },
    { name: 'Antes / depois', cat: 'Carousel', installs: 890 },
    { name: 'Oferta com prova', cat: 'Ads', installs: 640 },
    { name: 'Thread autoridade', cat: 'Social', installs: 510 },
    { name: 'Newsletter semanal', cat: 'Email', installs: 430 },
    { name: 'Reels 30s benefícios', cat: 'Video', installs: 780 },
  ],
  integrations: [
    { name: 'Instagram', status: 'Conectado' },
    { name: 'LinkedIn', status: 'Conectado' },
    { name: 'TikTok', status: 'Conectado' },
    { name: 'Meta Ads', status: 'Pendente' },
    { name: 'Google Drive', status: 'Conectado' },
    { name: 'Slack', status: 'Não conectado' },
  ],
};
