import {
  Image as ImageIcon,
  Layers,
  PenSquare,
  Megaphone,
  Mail,
  Clapperboard,
  CalendarRange,
  FolderOpen,
  LayoutTemplate,
  Tags,
  CalendarDays,
  Bot,
  ListTodo,
  Plug,
  Blocks,
  BarChart3,
  LineChart,
  Share2,
  CreditCard,
  Settings,
} from 'lucide-react';
import type { FeatureCardDef, FeatureSectionId } from './unified-onboarding.types';

export const FEATURE_SECTIONS: {
  id: FeatureSectionId;
  titleKey: string;
  titleDefault: string;
}[] = [
  { id: 'create', titleKey: 'onboarding_section_create', titleDefault: 'Criar' },
  { id: 'library', titleKey: 'onboarding_section_library', titleDefault: 'Biblioteca' },
  { id: 'operate', titleKey: 'onboarding_section_operate', titleDefault: 'Operar' },
  { id: 'measure', titleKey: 'onboarding_section_measure', titleDefault: 'Medir' },
  { id: 'account', titleKey: 'onboarding_section_account', titleDefault: 'Conta' },
];

export const FEATURE_CATALOG: FeatureCardDef[] = [
  {
    id: 'ai-generate-images',
    section: 'create',
    titleKey: 'onboarding_feat_ai_images_title',
    titleDefault: 'Gerar imagens com IA',
    descriptionKey: 'onboarding_feat_ai_images_desc',
    descriptionDefault: 'Crie carrosséis e peças visuais com a identidade da marca.',
    whyKey: 'onboarding_feat_ai_images_why',
    whyDefault: 'É o atalho do DNA ao primeiro conteúdo publicável.',
    path: '/ai-generate-images',
    icon: ImageIcon,
  },
  {
    id: 'content-swipe',
    section: 'create',
    titleKey: 'onboarding_feat_swipe_title',
    titleDefault: 'Content Swipe',
    descriptionKey: 'onboarding_feat_swipe_desc',
    descriptionDefault: 'Inspire-se em referências e adapte ideias em segundos.',
    whyKey: 'onboarding_feat_swipe_why',
    whyDefault: 'Acelera o brainstorming com exemplos reais.',
    path: '/content-swipe',
    icon: Layers,
  },
  {
    id: 'social-posts',
    section: 'create',
    titleKey: 'onboarding_feat_social_title',
    titleDefault: 'Criativos / Posts',
    descriptionKey: 'onboarding_feat_social_desc',
    descriptionDefault: 'Gere posts sociais com copy alinhada à marca.',
    whyKey: 'onboarding_feat_social_why',
    whyDefault: 'Mantém o feed consistente sem começar do zero.',
    path: '/social-posts',
    icon: PenSquare,
  },
  {
    id: 'ad-creatives',
    section: 'create',
    titleKey: 'onboarding_feat_ads_title',
    titleDefault: 'Ad Creatives',
    descriptionKey: 'onboarding_feat_ads_desc',
    descriptionDefault: 'Produza criativos de anúncio prontos para mídia paga.',
    whyKey: 'onboarding_feat_ads_why',
    whyDefault: 'Liga conteúdo orgânico a campanhas pagas.',
    path: '/social-posts/ad-creatives',
    icon: Megaphone,
  },
  {
    id: 'email-campaigns',
    section: 'create',
    titleKey: 'onboarding_feat_email_title',
    titleDefault: 'Campanhas de e-mail',
    descriptionKey: 'onboarding_feat_email_desc',
    descriptionDefault: 'Monte campanhas e sequências de e-mail com IA.',
    whyKey: 'onboarding_feat_email_why',
    whyDefault: 'Expande o conteúdo além das redes sociais.',
    path: '/social-posts/email-campaigns',
    icon: Mail,
  },
  {
    id: 'video-scripts',
    section: 'create',
    titleKey: 'onboarding_feat_video_title',
    titleDefault: 'Roteiros de vídeo',
    descriptionKey: 'onboarding_feat_video_desc',
    descriptionDefault: 'Gere roteiros curtos para Reels, Shorts e TikTok.',
    whyKey: 'onboarding_feat_video_why',
    whyDefault: 'Facilita a produção de vídeo com a voz da marca.',
    path: '/social-posts/video-scripts',
    icon: Clapperboard,
  },
  {
    id: 'editorial',
    section: 'create',
    titleKey: 'onboarding_feat_editorial_title',
    titleDefault: 'Plano editorial',
    descriptionKey: 'onboarding_feat_editorial_desc',
    descriptionDefault: 'Organize pilares, slots e geração automática de conteúdo.',
    whyKey: 'onboarding_feat_editorial_why',
    whyDefault: 'Transforma ideias soltas em calendário recorrente.',
    path: '/editorial',
    icon: CalendarRange,
  },
  {
    id: 'media',
    section: 'library',
    titleKey: 'onboarding_feat_media_title',
    titleDefault: 'Media',
    descriptionKey: 'onboarding_feat_media_desc',
    descriptionDefault: 'Biblioteca central de imagens, vídeos e assets.',
    whyKey: 'onboarding_feat_media_why',
    whyDefault: 'Reutilize arquivos em posts e carrosséis.',
    path: '/media',
    icon: FolderOpen,
  },
  {
    id: 'templates',
    section: 'library',
    titleKey: 'onboarding_feat_templates_title',
    titleDefault: 'Templates',
    descriptionKey: 'onboarding_feat_templates_desc',
    descriptionDefault: 'Marketplace de templates prontos para adaptar.',
    whyKey: 'onboarding_feat_templates_why',
    whyDefault: 'Economiza tempo de design em formatos recorrentes.',
    path: '/template-marketplace',
    icon: LayoutTemplate,
  },
  {
    id: 'brands',
    section: 'library',
    titleKey: 'onboarding_feat_brands_title',
    titleDefault: 'Brands',
    descriptionKey: 'onboarding_feat_brands_desc',
    descriptionDefault: 'Gerencie múltiplas marcas, DNA e assets.',
    whyKey: 'onboarding_feat_brands_why',
    whyDefault: 'Base de tudo que a IA gera no produto.',
    path: '/brands',
    icon: Tags,
  },
  {
    id: 'launches',
    section: 'operate',
    titleKey: 'onboarding_feat_launches_title',
    titleDefault: 'Calendário',
    descriptionKey: 'onboarding_feat_launches_desc',
    descriptionDefault: 'Agende e publique posts em todos os canais.',
    whyKey: 'onboarding_feat_launches_why',
    whyDefault: 'Onde o conteúdo vira presença real.',
    path: '/launches',
    icon: CalendarDays,
  },
  {
    id: 'agents',
    section: 'operate',
    titleKey: 'onboarding_feat_agents_title',
    titleDefault: 'Agents',
    descriptionKey: 'onboarding_feat_agents_desc',
    descriptionDefault: 'Automações e agentes de conteúdo com IA.',
    whyKey: 'onboarding_feat_agents_why',
    whyDefault: 'Escala tarefas repetidas do time.',
    path: '/agents',
    icon: Bot,
  },
  {
    id: 'jobs',
    section: 'operate',
    titleKey: 'onboarding_feat_jobs_title',
    titleDefault: 'Jobs',
    descriptionKey: 'onboarding_feat_jobs_desc',
    descriptionDefault: 'Acompanhe gerações e filas assíncronas.',
    whyKey: 'onboarding_feat_jobs_why',
    whyDefault: 'Transparência do que a IA está processando.',
    path: '/jobs',
    icon: ListTodo,
  },
  {
    id: 'plugs',
    section: 'operate',
    titleKey: 'onboarding_feat_plugs_title',
    titleDefault: 'Plugs',
    descriptionKey: 'onboarding_feat_plugs_desc',
    descriptionDefault: 'Conectores e automações pontuais por canal.',
    whyKey: 'onboarding_feat_plugs_why',
    whyDefault: 'Estende o fluxo sem código.',
    path: '/plugs',
    icon: Plug,
  },
  {
    id: 'third-party',
    section: 'operate',
    titleKey: 'onboarding_feat_third_title',
    titleDefault: 'Integrações',
    descriptionKey: 'onboarding_feat_third_desc',
    descriptionDefault: 'Apps e serviços de terceiros conectados.',
    whyKey: 'onboarding_feat_third_why',
    whyDefault: 'Liga o ContentFlow ao restante do stack.',
    path: '/third-party',
    icon: Blocks,
  },
  {
    id: 'analytics',
    section: 'measure',
    titleKey: 'onboarding_feat_analytics_title',
    titleDefault: 'Analytics',
    descriptionKey: 'onboarding_feat_analytics_desc',
    descriptionDefault: 'Métricas gerais de publicações por canal.',
    whyKey: 'onboarding_feat_analytics_why',
    whyDefault: 'Fecha o ciclo criar → publicar → aprender.',
    path: '/analytics',
    icon: BarChart3,
  },
  {
    id: 'carousel-analytics',
    section: 'measure',
    titleKey: 'onboarding_feat_carousel_analytics_title',
    titleDefault: 'Carousel Performance',
    descriptionKey: 'onboarding_feat_carousel_analytics_desc',
    descriptionDefault: 'Performance detalhada dos carrosséis.',
    whyKey: 'onboarding_feat_carousel_analytics_why',
    whyDefault: 'Otimiza o formato mais usado no studio.',
    path: '/analytics/carousel',
    icon: LineChart,
  },
  {
    id: 'affiliates',
    section: 'account',
    titleKey: 'onboarding_feat_affiliates_title',
    titleDefault: 'Afiliados',
    descriptionKey: 'onboarding_feat_affiliates_desc',
    descriptionDefault: 'Programa de indicação e comissões.',
    whyKey: 'onboarding_feat_affiliates_why',
    whyDefault: 'Monetize indicando o produto.',
    path: '/affiliates',
    icon: Share2,
  },
  {
    id: 'billing',
    section: 'account',
    titleKey: 'onboarding_feat_billing_title',
    titleDefault: 'Planos e billing',
    descriptionKey: 'onboarding_feat_billing_desc',
    descriptionDefault: 'Assinatura, trial e limites do plano.',
    whyKey: 'onboarding_feat_billing_why',
    whyDefault: 'Evita bloqueio no meio da geração.',
    path: '/billing',
    icon: CreditCard,
  },
  {
    id: 'settings',
    section: 'account',
    titleKey: 'onboarding_feat_settings_title',
    titleDefault: 'Configurações',
    descriptionKey: 'onboarding_feat_settings_desc',
    descriptionDefault: 'Time, preferências e organização.',
    whyKey: 'onboarding_feat_settings_why',
    whyDefault: 'Ajustes finos da conta e permissões.',
    path: '/settings',
    icon: Settings,
  },
];
